[package]
name = "copse"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29"
pulldown-cmark = "0.13.4"
ratatui = "0.30"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.4"
uuid = { version = "1.26.0", features = ["v4"] }
